apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
  namespace: fiapstore
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=catalog-db;Port=5432;Database=Db.Catalog;Username=postgres;Password=rooot1234!!"
  Jwt__Key: "IkV6/I+/6WtC4xTRDjLMdwWl0jkt6UAU2R0NUwsL7fI="
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "rooot1234!!"
  POSTGRES_DB: "Db.Catalog"
  ElasticSettings__ApiKey: "ELASTICSETTINGS_APIKEY_PLACEHOLDER"
  ElasticSettings__CloudId: "ELASTICSETTINGS_CLOUDID_PLACEHOLDER"
  ElasticSettings__UseCloud: "ELASTICSETTINGS_USECLOUD_PLACEHOLDER"
  AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID_PLACEHOLDER"
  AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY_PLACEHOLDER"
  AWS_DEFAULT_REGION: "AWS_DEFAULT_REGION_PLACEHOLDER"
